# Usar una imagen oficial de Python ligera
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el script a la carpeta de trabajo del contenedor
COPY main.py .

# Comando que se ejecutará cuando inicie el contenedor
CMD ["python", "main.py"]
